### ISSUE TITLE
Bug found while  trying to turn on the recitaion audio.

### ISSUE THREAD

**Issue by huwaid** [frrahat/Quran-For-My-Android#15]
#### Expected behavior
App should be able to play the audio of the selected Surah when we turn on the recitaion audio.

#### Actual behavior
We are not able to listen the audio of the selected Surah as it shows the error of "Audio file not found in the folder".

#### How to reproduce
Launch the app.

Select any option from the Primary text selection.

Press  the options menu and select any Surah.

Click on the three dots(settings).

Turn on the recitaion audio.

Now click on the play button and try to play the audio of Surah.

A message will pop up saying "Audio file not found in the folder".

* App : Quran for my android 1.6.0(GPL-2.0+)
* Operating system: Android Naugat.
Redmi 5a

#### Recording Of The Bug

https://youtu.be/8vrYoxjZy4Q

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@huwaid/bug-found-which-trying-to-turn-on-the-recitaion-audio">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by frrahat** [comment]
Hi @huwaid, It is not a bug but the expected behaviour actually. It is explained in the **Recitation Audio** section in the **Help** menu of the app.

So audio files needs to be kept there to be able to play the recitation. You can go to http://www.everyayah.com to download the recitation files you want to play.
